[package]
name = "totp"
version = "0.1.0"
authors = ["Stipe Kotarac <stipe@kotarac.net>"]
license = "MIT"
description = "CLI tool for generating TOTP codes."
homepage = "https://github.com/kotarac/totp"
repository = "https://github.com/kotarac/totp"

[dependencies]
oath = "0.1.4"
base32 = "0.3.1"
